GET http://localhost:3003/api/products

###

GET http://localhost:3003/api/products/69ca6bc95344f2049af91147

###
POST http://localhost:3003/api/products
Content-Type: application/json

# {
#     "name": "Cappuccino",
#     "description": "Espresso with steamed milk and a layer of foam on top.",
#     "price": 3.5
# }
{
    "name": "white coffee",
    "description": "A simple and classic choice, white coffee is made by brewing ground coffee with steamed milk.",
    "price": 2.5
}

###
DELETE http://localhost:3003/api/products/69ce4e46746dbdfbf2fe9501

###
PUT http://localhost:3003/api/products/69ce55c79a4ef7e84f0dcc9c
Content-Type: application/json

{
    "name": "Latte",
    "description": "Espresso with steamed milk and a small amount of foam on top.",
    "price": 3.0
}